### ISSUE TITLE
deployment to heroku

### ISSUE THREAD

**Issue by mshahat** [kmaida/rota-slackbot#38]
Hello, 

thanks a ton for developing this app. i'm looking to use it to try and rotate a few team chores like standups moderation and so. I'd like to deploy the app to heroku

1. were others successful with deploying to heroku fully? 
2. do we have instructions or even notes somewhere that i could refer to? 

Cheers, 

/cc @mramadan88

**Comment by kmaida** [comment]
I deploy my Slackbots to Heroku (it's my primary deployment / hosting), and Rota is successfully in production on Heroku.

The README for this repo has the following information in it:

If you want fast, easy deployments with CI/CD features and don't want to deal with devops, domains, or configuring SSL, I recommend a hobby dyno on Heroku.

Note: A free dyno on Heroku will not work well because the app will sleep after 30 minutes, which causes long response times when it needs to wake back up.

If using DigitalOcean (or a similar VPS), input your production environment variables in a .env file on your server.

If using Heroku, input your production environment variables in your Heroku app settings.

Whatever deployment option you choose, once you have a public domain for your Slack app with SSL, go into your production Slack app settings and update the Event Subscriptions Request URL to https://your-public-url/slack/events.

**Comment by mshahat** [comment]
Extremely useful and thanks very much fir the elaborate explanation. We've successfully deployed to heroku too, yet to test more. 

/CC @mramadan88

**Comment by kmaida** [comment]
Glad to hear it! Let me know if you run into any issues. I'm going to close this issue, but feel free to open a new one if there are any specific challenges you run into.
